// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9PvXDnUQAeKeOxmQGfwBA2ksdmFzP1wk',
    appId: '1:666847721511:web:b9a371edc39db6cfc43602',
    messagingSenderId: '666847721511',
    projectId: 'chatapp-e8112',
    authDomain: 'chatapp-e8112.firebaseapp.com',
    storageBucket: 'chatapp-e8112.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZtYQL2SzgcJMpbY6pYk94jkrreCw8_gw',
    appId: '1:666847721511:android:271bf976cf9d2f9cc43602',
    messagingSenderId: '666847721511',
    projectId: 'chatapp-e8112',
    storageBucket: 'chatapp-e8112.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4u9_0_kIRHQQHtaqgH_efs1i7Cb7LkE8',
    appId: '1:666847721511:ios:db2f0a5aab6fb177c43602',
    messagingSenderId: '666847721511',
    projectId: 'chatapp-e8112',
    storageBucket: 'chatapp-e8112.firebasestorage.app',
    iosBundleId: 'com.chat.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4u9_0_kIRHQQHtaqgH_efs1i7Cb7LkE8',
    appId: '1:666847721511:ios:db2f0a5aab6fb177c43602',
    messagingSenderId: '666847721511',
    projectId: 'chatapp-e8112',
    storageBucket: 'chatapp-e8112.firebasestorage.app',
    iosBundleId: 'com.chat.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9PvXDnUQAeKeOxmQGfwBA2ksdmFzP1wk',
    appId: '1:666847721511:web:8b079515c48fe316c43602',
    messagingSenderId: '666847721511',
    projectId: 'chatapp-e8112',
    authDomain: 'chatapp-e8112.firebaseapp.com',
    storageBucket: 'chatapp-e8112.firebasestorage.app',
  );
}
